/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module crc3_eval(i_data, i_poly, i_crc, o_crc);
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  wire [5:0] crc_tmp;
  wire [31:0] i;
  input [1:0] i_crc;
  input [3:0] i_data;
  input [2:0] i_poly;
  output [1:0] o_crc;
  wire [1:0] poly_tmp;
  assign _0_ = i_poly[0] ^ i_crc[0];
  assign o_crc[0] = i_data[0] ? _0_ : i_crc[0];
  assign _1_ = i_poly[0] ^ i_crc[1];
  assign _2_ = i_data[1] ? _1_ : i_crc[1];
  assign _3_ = _2_ ^ i_poly[1];
  assign o_crc[1] = i_data[0] ? _3_ : _2_;
  assign crc_tmp = { 4'hx, o_crc };
  assign i = 32'd4294967295;
  assign poly_tmp = i_poly[2:1];
endmodule
