/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module thermometer2U2(i_argA, o_result);
  wire [31:0] i;
  input [1:0] i_argA;
  output o_result;
  assign i = 32'd2;
  assign o_result = i_argA[1];
endmodule
