/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module u2intoGray(i_argA, o_result);
  wire [1:0] _0_;
  input [1:0] i_argA;
  output [1:0] o_result;
  assign _0_[0] = i_argA[1] ^ i_argA[0];
  \$_DLATCH_P_  _2_ (
    .D(_0_[0]),
    .E(1'hx),
    .Q(o_result[0])
  );
  \$_DLATCH_P_  _3_ (
    .D(i_argA[1]),
    .E(1'hx),
    .Q(o_result[1])
  );
  assign _0_[1] = i_argA[1];
endmodule
