/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module zliczanie_1(i_argA, i_argB, o_result);
  wire [31:0] i;
  input [1:0] i_argA;
  input [1:0] i_argB;
  wire [1:0] licz;
  output [1:0] o_result;
  wire [1:0] wynik;
  assign o_result[0] = i_argB[1] ^ i_argB[0];
  assign o_result[1] = i_argB[1] & i_argB[0];
  assign i = 32'd2;
  assign licz = i_argB;
  assign wynik = o_result;
endmodule
